// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "3be8c82f-d6f7-4b6f-9d90-db9b683ad235";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onMoistureLevelChange();
void onManualModeChange();
void onManualPumpControlChange();
void onPumpStateChange();

int moistureLevel;
bool manualMode;
bool manualPumpControl;
bool pumpState;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(moistureLevel, READWRITE, ON_CHANGE, onMoistureLevelChange);
  ArduinoCloud.addProperty(manualMode, READWRITE, ON_CHANGE, onManualModeChange);
  ArduinoCloud.addProperty(manualPumpControl, READWRITE, ON_CHANGE, onManualPumpControlChange);
  ArduinoCloud.addProperty(pumpState, READWRITE, ON_CHANGE, onPumpStateChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
